exports.seed = async function (knex) {
    // Deletes ALL existing entries
    await knex('itinerary').del();
    await knex('itinerary').insert([
        {
            itinerary_id: '4829650317',
            user_id: '9318657024',
            user_name: 'RoamingRaven',
            user_icon: 'http://localhost:8080/images/users/avery.jpg',
            city: 'Tokyo, Japan',
            budget: '$$',
            views: 400,
            likes: 70,
            ratings: 4.5,
            duration: 5,
            city_img: 'http://localhost:8080/images/cities/tokyo1.jpg',
            trip_title: "Experience the Best of Tokyo: From Street Food to High Fashion",
            date: '05/11/2019',
            description: "Tokyo is a bustling metropolis known for its neon-lit streets, towering skyscrapers, and cutting-edge technology. It's a city that seamlessly blends modernity with tradition, with ancient shrines and temples nestled among its futuristic architecture.",

        },
        {
            itinerary_id: '1208376945',
            user_id: '6815302947',
            user_name: 'WanderingWave',
            user_icon: 'http://localhost:8080/images/users/maya.jpg',
            city: 'Tokyo, Japan',
            budget: '$$$',
            views: 789,
            likes: 45,
            ratings: 4.7,
            duration: 3,
            city_img: 'http://localhost:8080/images/cities/tokyo2.jpg',
            trip_title: "Tokyo: Where Tradition Meets Technology",
            date: '03/11/2018',
            description: "With a population of over 13 million, Tokyo is one of the world's largest cities, offering visitors an endless array of activities and experiences. From its world-class museums and art galleries to its vibrant nightlife and diverse culinary scene, Tokyo has something for everyone.",

        },
        {
            itinerary_id: '6093842157',
            user_id: '8204639571',
            user_name: 'JetSetJenny',
            user_icon: 'http://localhost:8080/images/users/Jennifer.jpg',
            city: 'Tokyo, Japan',
            budget: '$$',
            views: 20,
            likes: 1,
            ratings: 4.2,
            duration: 10,
            city_img: 'http://localhost:8080/images/cities/tokyo3.jpg',
            trip_title: "Discover the Magic of Tokyo: A City of Endless Wonders",
            date: '05/11/2017',
            description: "Tokyo is a city of contrasts, where ancient traditions and modern innovations exist side by side. Visitors can marvel at the soaring Tokyo Tower, wander through the peaceful gardens of the Imperial Palace, or indulge in some of the world's best sushi and ramen.",
            // type: '',
        },
        {
            itinerary_id: '3584217960',
            user_id: '9025687431',
            user_name: 'DaringAmy',
            user_icon: 'http://localhost:8080/images/users/amy.png',
            city: 'London, Uk',
            budget: '$$',
            views: 99532,
            likes: 5622,
            ratings: 4,
            duration: 7,
            city_img: 'http://localhost:8080/images/cities/london1.jpg',
            trip_title: "London Calling: The Best of Britain's Capital City",
            date: '07/17/2021',
            description: "Discover the iconic sights and sounds of London, from the majestic Tower Bridge to the bustling West End theatre district.",

        },
        {
            itinerary_id: '7491058362',
            user_id: '3152908764',
            user_name: 'NomadNate',
            user_icon: 'http://localhost:8080/images/users/Nathan.jpg',
            city: 'London, Uk',
            budget: '$$$',
            views: 6789,
            likes: 255,
            ratings: 4.5,
            duration: 3,
            city_img: 'http://localhost:8080/images/cities/london2.jpg',
            trip_title: "Uncovering London's Hidden Gems: A Journey off the Beaten Path",
            date: '07/12/2021',
            description: "Discover the lesser-known, hidden corners of London, from quirky independent shops and markets to picturesque hidden gardens and parks.",
            // type: '',
        },
        {
            itinerary_id: '9316742085',
            user_id: '6078925341',
            user_name: 'BrazilianLocalJa',
            user_icon: 'http://localhost:8080/images/users/jess.png',
            city: 'London, Uk',
            budget: '$$',
            views: 5671,
            likes: 468,
            ratings: 4.8,
            duration: 7,
            city_img: 'http://localhost:8080/images/cities/london3.jpg',
            trip_title: "London: A City of Culture and History",
            date: '03/11/2019',
            description: "Explore London's rich history and cultural heritage, from the iconic landmarks of Buckingham Palace and the Houses of Parliament to world-renowned museums like the British Museum and the National Gallery.",
            // type: '',
        },
        {
            itinerary_id: '2065813794',
            user_id: '9318657024',
            user_name: 'RoamingRaven',
            user_icon: 'http://localhost:8080/images/users/avery.jpg',
            city: 'New York City, USA',
            budget: '$$$$',
            views: 6789,
            likes: 2363,
            ratings: 4.1,
            duration: 3,
            city_img: 'http://localhost:8080/images/cities/nyc5.jpg',
            trip_title: "The Big Apple Awaits: Exploring the Best of New York City",
            date: '06/16/2022',
            description: "Discover the vibrant energy of NYC, from the iconic landmarks of the Statue of Liberty and the Empire State Building to the world-famous museums and galleries of Museum Mile.",
            // type: '',
        },
        {
            itinerary_id: '8576931024',
            user_id: '9025687431',
            user_name: 'DaringAmy',
            user_icon: 'http://localhost:8080/images/users/amy.png',
            city: 'New York City, USA',
            budget: '$$',
            views: 66943,
            likes: 8622,
            ratings: 4,
            duration: 2,
            city_img: 'http://localhost:8080/images/cities/nyc1.jpg',
            trip_title: "Tasting the City: A Culinary Journey Through New York's Neighborhoods",
            date: '02/11/2023',
            description: "Experience the diverse flavors of NYC, from the traditional pizza and bagels of Little Italy to the spicy flavors of Chinatown and the trendy cafes and eateries of Brooklyn.",
            // type: '',
        },
        {
            itinerary_id: '5132879460',
            user_id: '7639841250',
            user_name: 'AdventurousAnna',
            user_icon: 'http://localhost:8080/images/users/anna.jpg',
            city: 'New York City, USA',
            budget: '$$$',
            views: 65300,
            likes: 5557,
            ratings: 4.6,
            duration: 6,
            city_img: 'http://localhost:8080/images/cities/nyc2.jpg',
            trip_title: "New York After Dark: A Nightlife Tour of the City That Never Sleeps",
            date: '08/15/2022',
            description: "Explore NYC's buzzing nightlife scene, from the chic rooftop bars of Manhattan to the legendary jazz clubs and music venues of Greenwich Village.",
            // type: '',
        },
        {
            itinerary_id: '9753216840',
            user_id: '3152908764',
            user_name: 'NomadNate',
            user_icon: 'http://localhost:8080/images/users/Nathan.jpg',
            city: 'New York City, USA',
            budget: '$$',
            views: 11001,
            likes: 557,
            ratings: 4.5,
            duration: 2,
            city_img: 'http://localhost:8080/images/cities/nyc3.jpg',
            trip_title: "Beyond the Tourist Trail: Uncovering NYC's Hidden Gems",
            date: '07/24/2022',
            description: "Discover the lesser-known attractions and off-the-beaten-path neighborhoods of NYC, from the colorful street art of Bushwick to the tranquil gardens and parks of Upper Manhattan.",
            // type: '',
        },
        {
            itinerary_id: '6743192850',
            user_id: '8204639571',
            user_name: 'JetSetJenny',
            user_icon: 'http://localhost:8080/images/users/Jennifer.jpg',
            city: 'New York City, USA',
            budget: '$$$$',
            views: 5,
            likes: 0,
            ratings: 3.9,
            duration: 7,
            city_img: 'http://localhost:8080/images/cities/nyc4.jpg',
            trip_title: "Shopping Spree in the City: Exploring NYC's Best Shopping Districts",
            date: '05/21/2022',
            description: "Indulge in a shopping adventure through NYC's top retail destinations, from the high-end boutiques of Fifth Avenue to the vintage shops and markets of Brooklyn.",
            // type: '',
        },
        {
            itinerary_id: '1248630975',
            user_id: '4976132085',
            user_name: 'GlobeTrotterGuy',
            user_icon: 'http://localhost:8080/images/users/Luke.jpg',
            city: 'Chicago, USA',
            budget: '$$$',
            views: 563,
            likes: 212,
            ratings: 4.5,
            duration: 5,
            city_img: 'http://localhost:8080/images/cities/chicago2.jpg',
            trip_title: "Taste of Chicago: A Culinary Journey Through the City's Diverse Neighborhoods",
            date: '05/14/2022',
            description: "Discover the vibrant energy of Chicago, from the iconic skyscrapers of the Loop to the world-class museums and galleries of Museum Campus.",
            // type: '',
        },
        {
            itinerary_id: '3560829147',
            user_id: '6815302947',
            user_name: 'WanderingWave',
            user_icon: 'http://localhost:8080/images/users/maya.jpg',
            city: 'Chicago, USA',
            budget: '$$',
            views: 7890,
            likes: 567,
            ratings: 3.9,
            duration: 3,
            city_img: 'http://localhost:8080/images/cities/chicago1.jpg',
            trip_title: "The Windy City Adventure: Exploring the Best of Chicago",
            date: '07/17/2021',
            description: "Discover the vibrant energy of Chicago, from the iconic skyscrapers of the Loop to the world-class museums and galleries of Museum Campus.",
        },
        {
            itinerary_id: '6925108347',
            user_id: '3152908764',
            user_name: 'NomadNate',
            user_icon: 'http://localhost:8080/images/users/Nathan.jpg',
            city: 'Paris, France',
            budget: '$$$$',
            views: 45890,
            likes: 200,
            ratings: 4.9,
            duration: 5,
            city_img: 'http://localhost:8080/images/cities/paris2.jpg',
            trip_title: "A Romantic Journey through Paris: Uncovering the City's Hidden Charms",
            date: '05/14/2017',
            description: " Indulge in the romantic atmosphere of Paris, exploring the winding streets of Montmartre and the charming hidden squares of the Marais.",
            // type: '',
        },
        {
            itinerary_id: '8316092754',
            user_id: '9025687431',
            user_name: 'DaringAmy',
            user_icon: 'http://localhost:8080/images/users/amy.png',
            city: 'Paris, France',
            budget: '$$$',
            views: 11582,
            likes: 9986,
            ratings: 4.3,
            duration: 4,
            city_img: 'http://localhost:8080/images/cities/paris1.jpg',
            trip_title: "Parisian Delights: A Culinary Tour of the City's Best Restaurants and Markets",
            date: '11/11/2022',
            description: "Savor the flavors of Paris, from the classic croissants and café au lait of its iconic cafes to the Michelin-starred restaurants and gourmet markets.",
            // type: '',
        },
        {
            itinerary_id: '2750691483',
            user_id: '9318657024',
            user_name: 'RoamingRaven',
            user_icon: 'http://localhost:8080/images/users/avery.jpg',
            city: 'Paris, France',
            budget: '$$',
            views: 5679,
            likes: 2343,
            ratings: 4.5,
            duration: 3,
            city_img: 'http://localhost:8080/images/cities/paris3.jpg',
            trip_title: "Beyond the Tourist Trail: Uncovering Paris's Hidden Gems",
            date: '09/20/2021',
            description: "Discover the lesser-known attractions and off-the-beaten-path neighborhoods of Paris, from the bohemian atmosphere of Canal Saint-Martin to the picturesque vineyards of Montmartre.",
            // type: '',
        },
        {
            itinerary_id: '4091567283',
            user_id: '7639841250',
            user_name: 'AdventurousAnna',
            user_icon: 'http://localhost:8080/images/users/anna.jpg',
            city: 'Paris, France',
            budget: '$$$',
            views: 99521,
            likes: 5877,
            ratings: 4.1,
            duration: 7,
            city_img: 'http://localhost:8080/images/cities/paris4.jpg',
            trip_title: "The City of Lights: Discovering the Best of Paris",
            date: '10/01/2021',
            description: "Immerse yourself in the magical energy of Paris, from the iconic Eiffel Tower and Champs-Élysées to the world-renowned museums like the Louvre and Musée d'Orsay.",
            // type: '',
        },
        {
            itinerary_id: '6280351974',
            user_id: '4976132085',
            user_name: 'GlobeTrotterGuy',
            user_icon: 'http://localhost:8080/images/users/Luke.jpg',
            city: 'Paris, France',
            budget: '$$',
            views: 1930,
            likes: 378,
            ratings: 4.5,
            duration: 3,
            city_img: 'http://localhost:8080/images/cities/paris5.jpg',
            trip_title: "Artistic Paris: Exploring the City's Vibrant Art Scene",
            date: '09/15/2019',
            description: "Immerse yourself in the world of art in Paris, from the stunning masterpieces of the Musée de l'Orangerie and Centre Pompidou to the colorful street art of the Canal Saint-Martin and Belleville neighborhoods.",
            // type: '',
        },
        {
            itinerary_id: '9378461025',
            user_id: '6078925341',
            user_name: 'BrazilianLocalJa',
            user_icon: 'http://localhost:8080/images/users/jess.png',
            city: 'Rome, Italy',
            budget: '$$',
            views: 9722,
            likes: 678,
            ratings: 4.2,
            duration: 6,
            city_img: 'http://localhost:8080/images/cities/italianfood.jpg',
            trip_title: "A Culinary Journey through Rome: Indulging in the Flavors of Italy",
            date: '06/11/2021',
            description: "Savor the diverse flavors of Rome, from the classic pizza and pasta dishes of the city's trattorias to the local specialties like supplì and carciofi alla romana.",
            // type: '',
        },
        {
            itinerary_id: '5082371649',
            user_id: '6078925341',
            user_name: 'BrazilianLocalJa',
            user_icon: 'http://localhost:8080/images/users/jess.png',
            city: 'Rome, Italy',
            budget: '$$',
            views: 90075,
            likes: 4267,
            ratings: 4.0,
            duration: 5,
            city_img: 'http://localhost:8080/images/cities/rome1.jpg',
            trip_title: "Eternal Rome: Discovering the Best of the Italian Capital",
            date: '04/16/2022',
            description: "Explore the ancient and modern wonders of Rome, from the iconic Colosseum and Roman Forum to the world-renowned Vatican Museums and Sistine Chapel.",
            // type: '',
        },
        {
            itinerary_id: '4265809731',
            user_id: '9025687431',
            user_name: 'DaringAmy',
            user_icon: 'http://localhost:8080/images/users/amy.png',
            city: 'Milan, Italy',
            budget: '$$',
            views: 77457,
            likes: 9975,
            ratings: 4.9,
            duration: 3,
            city_img: 'http://localhost:8080/images/cities/milan.jpg',
            trip_title: "Fashion and Culture in Milan: A Journey through Italy's Stylish Capital",
            date: '06/16/2022',
            description: "Immerse yourself in the fashion and culture of Milan, from the iconic Galleria Vittorio Emanuele II and the fashionable boutiques of Via Montenapoleone to the stunning works of art and architecture at the Pinacoteca di Brera and the imposing Sforza Castle.Enjoy the delicious Milanese cuisine, including classic dishes like risotto alla milanese and ossobuco.",
            // type: '',
        },
        {
            itinerary_id: '9481750236',
            user_id: '3152908764',
            user_name: 'NomadNate',
            user_icon: 'http://localhost:8080/images/users/Nathan.jpg',
            city: 'Venice, Italy',
            budget: '$$$',
            views: 567,
            likes: 239,
            ratings: 4.2,
            duration: 3,
            city_img: 'http://localhost:8080/images/cities/venice.jpg',
            trip_title: "Venice: The City of Canals and Romance",
            date: '05/11/2019',
            description: "Experience the magic of Venice, exploring the winding canals and bridges that connect the city's iconic landmarks like Piazza San Marco, the Doge's Palace, and the Rialto Bridge. Indulge in the romantic atmosphere of the city's narrow streets and picturesque squares, sampling local specialties like cicchetti and spritz along the way.",
            // type: '',
        },
        {
            itinerary_id: '3059274618',
            user_id: '6078925341',
            user_name: 'BrazilianLocalJa',
            user_icon: 'http://localhost:8080/images/users/jess.png',
            city: 'Bangkok, Thailand',
            budget: '$$',
            views: 88932,
            likes: 45001,
            ratings: 4.5,
            duration: 6,
            city_img: 'http://localhost:8080/images/cities/bangkok1.jpg',
            trip_title: "Bangkok by Night: Exploring the City's Vibrant Nightlife",
            date: '08/11/2022',
            description: "Experience the vibrant energy of Bangkok at night, from the colorful night markets and street food stalls to the lively bars and clubs along Khao San Road and Sukhumvit.",
            // type: '',
        },
        {
            itinerary_id: '6827315490',
            user_id: '6815302947',
            user_name: 'WanderingWave',
            user_icon: 'http://localhost:8080/images/users/maya.jpg',
            city: 'Bangkok, Thailand',
            budget: '$$',
            views: 12008,
            likes: 569,
            ratings: 3.5,
            duration: 10,
            city_img: 'http://localhost:8080/images/cities/bangkok4.jpg',
            trip_title: "Thai Culture and History in Bangkok: Discovering the City's Rich Heritage",
            date: '02/10/2019',
            description: "Immerse yourself in Thai culture and history, exploring the ornate temples and palaces like Wat Phra Kaew and the Grand Palace, and learning about the city's fascinating history at the National Museum and Jim Thompson House.",
            // type: '',
        },
        {
            itinerary_id: '9712356480',
            user_id: '4976132085',
            user_name: 'GlobeTrotterGuy',
            user_icon: 'http://localhost:8080/images/users/Luke.jpg',
            city: 'Bangkok, Thailand',
            budget: '$',
            views: 729,
            likes: 231,
            ratings: 4.1,
            duration: 2,
            city_img: 'http://localhost:8080/images/cities/bangkok3.jpg',
            trip_title: "A Culinary Journey through Bangkok: Indulging in the Flavors of Thailand",
            date: '03/01/2021',
            description: "Savor the diverse and delicious flavors of Bangkok's cuisine, from the classic pad Thai and green curry to the lesser-known regional specialties like khao soi and som tam. Take a cooking class and learn how to make these dishes yourself, and sample the street food like a local.",
            // type: '',
        },
        {
            itinerary_id: '7410293658',
            user_id: '3152908764',
            user_name: 'NomadNate',
            user_icon: 'http://localhost:8080/images/users/Nathan.jpg',
            city: 'Hanoi, Vietnam',
            budget: '$$',
            views: 2097,
            likes: 702,
            ratings: 4,
            duration: 6,
            city_img: 'http://localhost:8080/images/cities/hanoi2.jpg',
            trip_title: "Hanoi: Exploring the Capital's Rich History and Vibrant Street Life",
            date: '05/01/2018',
            description: "Discover the rich history and culture of Hanoi, from the ancient temples and pagodas like the Temple of Literature and the Tran Quoc Pagoda to the fascinating museums like the Ho Chi Minh Museum and the Vietnam Museum of Ethnology. Explore the vibrant street life of Hanoi, from the bustling markets and street food stalls to the charming cafes and art galleries of the Old Quarter.",
            // type: '',
        },
        {
            itinerary_id: '2106853479',
            user_id: '9025687431',
            user_name: 'DaringAmy',
            user_icon: 'http://localhost:8080/images/users/amy.png',
            city: 'Santorini, Greece',
            budget: '$$',
            views: 7795,
            likes: 347,
            ratings: 3.9,
            duration: 5,
            city_img: 'http://localhost:8080/images/cities/santorini2.jpg',
            trip_title: "Exploring Santorini's Ancient Past: Discovering the Island's Rich Archaeological Sites",
            date: '08/11/2019',
            description: "Uncover the island's ancient past by visiting the numerous archaeological sites scattered throughout Santorini. From the well-preserved Minoan city of Akrotiri to the ancient ruins of the Thera civilization at Ancient Thera, you'll get a glimpse into the island's fascinating history and culture.",
            // type: '',
        },
        {
            itinerary_id: '5672981340',
            user_id: '8204639571',
            user_name: 'JetSetJenny',
            user_icon: 'http://localhost:8080/images/users/Jennifer.jpg',
            city: 'Santorini, Greece',
            budget: '$$$',
            views: 74,
            likes: 10,
            ratings: 3.1,
            duration: 9,
            city_img: 'http://localhost:8080/images/cities/santorini1.jpg',
            date: '07/06/2021',
            trip_title: "Santorini Sunsets: Basking in the Island's Legendary Golden Hour",
            description: "Enjoy the legendary golden hour on the island of Santorini, where the sunsets are known as some of the most beautiful in the world. Take a sunset cruise or find a perfect spot to watch the sun dip below the Aegean Sea, painting the sky in brilliant shades of orange and pink.",
            // type: '',
        },
        {
            itinerary_id: '8374051962',
            user_id: '9025687431',
            user_name: 'DaringAmy',
            user_icon: 'http://localhost:8080/images/users/amy.png',
            city: 'Amsterdam, Netherland',
            budget: '$$',
            views: 56890,
            likes: 4227,
            ratings: 4.6,
            duration: 5,
            city_img: 'http://localhost:8080/images/cities/amsterdam1.jpg',
            trip_title: "Amsterdam on Two Wheels: Discovering the City's Bike Culture",
            date: '02/11/2021',
            description: "Get a taste of Amsterdam's bike culture by cycling through the city's picturesque neighborhoods and iconic landmarks. From the flower-filled fields of Keukenhof to the winding canals of the Jordaan district, you'll experience the city in a unique and authentic way.",
            // type: '',
        },
        {
            itinerary_id: '2634809157',
            user_id: '6078925341',
            user_name: 'BrazilianLocalJa',
            user_icon: 'http://localhost:8080/images/users/jess.png',
            city: 'Amsterdam, Netherland',
            budget: '$$',
            views: 5521,
            likes: 883,
            ratings: 4.2,
            duration: 3,
            city_img: 'http://localhost:8080/images/cities/amsterdam2.jpg',
            trip_title: "Amsterdam's Art Scene: A Journey through the City's Best Museums and Galleries",
            date: '08/11/2018',
            description: "Immerse yourself in Amsterdam's vibrant art scene, exploring the world-renowned museums like the Rijksmuseum and the Van Gogh Museum, as well as the contemporary galleries and street art around the city.",
            // type: '',
        },
        {
            itinerary_id: '4156092873',
            user_id: '4976132085',
            user_name: 'GlobeTrotterGuy',
            user_icon: 'http://localhost:8080/images/users/Luke.jpg',
            city: 'Amsterdam, Netherland',
            budget: '$$',
            views: 781,
            likes: 129,
            ratings: 4.2,
            duration: 4,
            city_img: 'http://localhost:8080/images/cities/amsterdam3.jpg',
            trip_title: "A Food Lover's Guide to Amsterdam: Savoring the City's Diverse Culinary Scene",
            date: '05/12/2019',
            description: "From the classic Dutch delicacies like stroopwafels and bitterballen to the international flavors of the city's many multicultural neighborhoods, Amsterdam is a food lover's paradise. Indulge in the city's diverse culinary scene, trying everything from Michelin-starred restaurants to the local street food.",
            // type: '',
        },
        {
            itinerary_id: '9267431508',
            user_id: '6078925341',
            user_name: 'BrazilianLocalJa',
            user_icon: 'http://localhost:8080/images/users/jess.png',
            city: 'Rio de janeiro, Brazil',
            budget: '$',
            views: 80991,
            likes: 67220,
            ratings: 4.9,
            duration: 10,
            city_img: 'http://localhost:8080/images/cities/rio4.jpg',
            trip_title: "Rio Carnival: Experiencing the City's Most Festive Season",
            date: '03/11/2021',
            description: "Join the samba rhythms and colorful costumes of the world-famous Rio Carnival, where the city comes alive in a week-long celebration of music, dance, and culture. From the samba schools' parades to the lively street parties, you'll experience the essence of Rio's spirit.",
            // type: '',
        },
        {
            itinerary_id: '1785934620',
            user_id: '6815302947',
            user_name: 'WanderingWave',
            user_icon: 'http://localhost:8080/images/users/maya.jpg',
            city: 'Rio de janeiro, Brazil',
            budget: '$$',
            views: 674,
            likes: 237,
            ratings: 4.1,
            duration: 5,
            city_img: 'http://localhost:8080/images/cities/rio1.jpg',
            trip_title: "Hiking in Rio: Exploring the City's Stunning Natural Beauty",
            date: '01/11/2022',
            description: "Discover the stunning natural beauty of Rio de Janeiro by hiking through the Tijuca National Park, the largest urban forest in the world. From the top of the Corcovado Mountain, where the iconic Christ the Redeemer statue stands, to the scenic trails of the Pedra da Gávea, you'll be rewarded with breathtaking views of the city's coastline.",
            // type: '',
        },
        {
            itinerary_id: '5801273649',
            user_id: '9025687431',
            user_name: 'DaringAmy',
            user_icon: 'http://localhost:8080/images/users/amy.png',
            city: 'Rio de janeiro, Brazil',
            budget: '$$',
            views: 88621,
            likes: 5990,
            ratings: 4.3,
            duration: 7,
            city_img: 'http://localhost:8080/images/cities/rio2.jpg',
            trip_title: "Rio Beaches: Relaxing in the City's Sun, Surf, and Sand",
            date: '02/11/2018',
            description: "Soak up the sun, surf, and sand at Rio's world-famous beaches, from the vibrant Copacabana and Ipanema to the quieter Praia Vermelha and Praia da Reserva. Whether you want to people-watch, play beach volleyball, or just relax with a caipirinha, Rio's beaches are the perfect spot to enjoy the city's laid-back lifestyle.",
            // type: '',
        },
        {
            itinerary_id: '3048562791',
            user_id: '3152908764',
            user_name: 'NomadNate',
            user_icon: 'http://localhost:8080/images/users/Nathan.jpg',
            city: 'Lisbon, Portugal',
            budget: '$$',
            views: 567,
            likes: 102,
            ratings: 4.2,
            duration: 6,
            city_img: 'http://localhost:8080/images/cities/lisbon4.jpg',
            trip_title: "Lisbon's Pastelarias: Sampling the City's Sweet Delights",
            date: '09/12/2019',
            description: "Savor the sweet delights of Lisbon's pastelarias, the city's traditional pastry shops, where you can indulge in the iconic Pastel de Nata, the sweet and creamy egg tart that originated in the city. From traditional bakeries to modern cafes, Lisbon's pastelarias offer a range of delicious treats to satisfy your sweet tooth.",
            // type: '',
        },
        {
            itinerary_id: '7913462058',
            user_id: '9025687431',
            user_name: 'DaringAmy',
            user_icon: 'http://localhost:8080/images/users/amy.png',
            city: 'Lisbon, Portugal',
            budget: '$$$',
            views: 55292,
            likes: 6790,
            ratings: 4.2,
            duration: 3,
            city_img: 'http://localhost:8080/images/cities/lisbon3.jpg',
            trip_title: "Lisbon's Hills and Views: Admiring the City's Scenic Beauty",
            date: '07/01/2019',
            description: "Climb Lisbon's hills and be rewarded with stunning views of the city and the Tagus River. From the historic Alfama district to the trendy Bairro Alto, Lisbon's neighborhoods offer unique vantage points to admire the city's colorful rooftops, landmarks, and sunsets.",
            // type: '',
        },
        {
            itinerary_id: '1056829374',
            user_id: '4976132085',
            user_name: 'GlobeTrotterGuy',
            user_icon: 'http://localhost:8080/images/users/Luke.jpg',
            city: 'Lisbon, Portugal',
            budget: '$',
            views: 567,
            likes: 213,
            ratings: 4.1,
            duration: 5,
            city_img: 'http://localhost:8080/images/cities/lisbon2.jpg',
            trip_title: "Discovering Lisbon's Street Art: A Tour of the City's Vibrant Murals and Graffiti",
            date: '04/12/2019',
            description: "Explore Lisbon's vibrant street art scene, from the colorful murals and graffiti adorning the city's alleys and buildings to the contemporary galleries and art festivals showcasing the best of urban art. Discover the diverse styles and voices of Lisbon's street art and the messages they convey.",
            // type: '',
        },
        {
            itinerary_id: '4291638750',
            user_id: '7639841250',
            user_name: 'AdventurousAnna',
            user_icon: 'http://localhost:8080/images/users/anna.jpg',
            city: 'Lisbon, Portugal',
            budget: '$$',
            views: 45190,
            likes: 2390,
            ratings: 3.2,
            duration: 3,
            city_img: 'http://localhost:8080/images/cities/lisbon1.jpg',
            trip_title: "Lisbon's Fado Music: Embracing the City's Soulful Melodies",
            date: '06/19/2022',
            description: " Immerse yourself in the soulful and melancholic music of Lisbon's Fado, a traditional Portuguese genre that tells stories of love, loss, and longing. From intimate performances in small taverns to grand shows at the city's iconic Fado houses, you'll experience the heart and soul of Lisbon's cultural heritage.",
            // type: '',
        },
        {
            itinerary_id: '6835912470',
            user_id: '9025687431',
            user_name: 'DaringAmy',
            user_icon: 'http://localhost:8080/images/users/amy.png',
            city: 'Reykjavik Iceland',
            budget: '$$',
            views: 77451,
            likes: 5422,
            ratings: 4.5,
            duration: 10,
            city_img: 'http://localhost:8080/images/cities/iceland2.jpg',
            trip_title: "Reykjavik's Hot Springs and Geysers: Soaking in Iceland's Natural Wonders",
            date: '02/11/2017',
            description: "Relax in Reykjavik's hot springs and geysers, natural wonders that are a result of the country's geothermal activity. From the popular Blue Lagoon to lesser-known hot springs and pools, you can take a dip in the warm and mineral-rich waters surrounded by Iceland's stunning landscapes.",
            // type: '',
        },
        {
            itinerary_id: '8452069371',
            user_id: '4819062379',
            user_name: 'AlexaA',
            user_icon: 'http://localhost:8080/images/users/alexa.png',
            city: 'Reykjavik Iceland',
            budget: '$$$',
            views: 692,
            likes: 340,
            ratings: 4.5,
            duration: 4,
            city_img: 'http://localhost:8080/images/cities/iceland1.jpg',
            trip_title: "Northern Lights: Witnessing Reykjavik's Spectacular Night Skies",
            date: '03/19/2022',
            description: "Experience the magic of the Aurora Borealis, the natural light show that illuminates Reykjavik's night skies in a mesmerizing display of green, pink, and purple hues. From guided tours to remote locations to viewing spots within the city, there are plenty of ways to witness this breathtaking phenomenon.",
            // type: '',
        },
        {
            itinerary_id: '5089362741',
            user_id: '2950384167',
            user_name: 'TumblingTom',
            user_icon: 'http://localhost:8080/images/users/tommy.jpg',
            city: 'Singapore',
            budget: '$$$',
            views: 50,
            likes: 6,
            ratings: 4.1,
            duration: 2,
            city_img: 'http://localhost:8080/images/cities/singapore1.jpg',
            trip_title: "Gardens by the Bay: Exploring Singapore's Futuristic Nature Park",
            date: '02/11/2022',
            description: "Immerse yourself in the breathtaking Gardens by the Bay, a futuristic nature park that showcases Singapore's commitment to sustainable and innovative design. From the iconic Supertrees and the Cloud Forest Dome to the lush gardens and art installations, Gardens by the Bay is a must-visit attraction for nature lovers and design enthusiasts.",
            // type: '',
        },
        {
            itinerary_id: '1298437605',
            user_id: '7639841250',
            user_name: 'AdventurousAnna',
            user_icon: 'http://localhost:8080/images/users/anna.jpg',
            city: 'Singapore',
            budget: '$$',
            views: 70002,
            likes: 6890,
            ratings: 4.2,
            duration: 3,
            city_img: 'http://localhost:8080/images/cities/singapore2.jpg',
            trip_title: "Singapore's Hawker Centers: Savoring the City's Culinary Treasures",
            date: '05/14/2022',
            description: "Indulge in the vibrant and diverse flavors of Singapore's hawker centers, where you can find a wide variety of local and international dishes at affordable prices. From the iconic Lau Pa Sat and Maxwell Food Centre to hidden gems in the city's neighborhoods, Singapore's hawker centers offer a true culinary adventure.",
            // type: '',
        },
        {
            itinerary_id: '2461587930',
            user_id: '4976132085',
            user_name: 'GlobeTrotterGuy',
            user_icon: 'http://localhost:8080/images/users/Luke.jpg',
            city: 'Barcelona, Spain',
            budget: '$$',
            views: 5672,
            likes: 123,
            ratings: 4.3,
            duration: 3,
            city_img: 'http://localhost:8080/images/cities/barcelona.jpg',
            trip_title: "Barcelona's Gothic Quarter: Exploring the City's Medieval Heart",
            date: '07/11/2019',
            description: "Step back in time as you wander through the winding streets and charming squares of Barcelona's Gothic Quarter, a historic neighborhood that is home to some of the city's most iconic landmarks, including the Gothic Cathedral and the Plaça del Rei.",
            // type: '',
        },
        {
            itinerary_id: '5729186304',
            user_id: '7639841250',
            user_name: 'AdventurousAnna',
            user_icon: 'http://localhost:8080/images/users/anna.jpg',
            city: 'Barcelona, Spain',
            budget: '$$',
            views: 14693,
            likes: 679,
            ratings: 3.6,
            duration: 3,
            city_img: 'http://localhost:8080/images/cities/barcelona1.jpg',
            trip_title: "Park Güell: Admiring Gaudí's Playful Masterpiece",
            date: '05/11/2016',
            description: "Marvel at the whimsical and colorful creations of Antoni Gaudí at Park Güell, a public park that features stunning mosaics, sculptures, and architecture. From the iconic dragon staircase to the terrace with panoramic views of the city, Park Güell is a must-see attraction for art and architecture lovers.",
            // type: '',
        },
        {
            itinerary_id: '8714620935',
            user_id: '9025687431',
            user_name: 'DaringAmy',
            user_icon: 'http://localhost:8080/images/users/amy.png',
            city: 'Madrid, Spain',
            budget: '$$',
            views: 5521,
            likes: 760,
            ratings: 4.8,
            duration: 4,
            city_img: 'http://localhost:8080/images/cities/madrid1.jpg',
            trip_title: "Madrid's Prado Museum: Discovering Spain's Artistic Treasures",
            date: '03/23/2019',
            description: "Explore one of the world's greatest art collections at the Prado Museum in Madrid, which houses masterpieces from renowned Spanish artists such as Francisco Goya, Diego Velázquez, and El Greco. From classical paintings to contemporary art, the Prado Museum offers a comprehensive overview of Spain's rich artistic heritage.",
            // type: '',
        },
        {
            itinerary_id: '3459726180',
            user_id: '2950384167',
            user_name: 'TumblingTom',
            user_icon: 'http://localhost:8080/images/users/tommy.jpg',
            city: 'Cairo, Eygpt',
            budget: '$$$',
            views: 70,
            likes: 24,
            ratings: 4.2,
            duration: 3,
            city_img: 'http://localhost:8080/images/cities/cairo.jpg',
            trip_title: "The Pyramids of Giza: Exploring the Wonders of the Ancient World",
            date: '07/01/2019',
            description: "Marvel at the awe-inspiring pyramids of Giza, one of the most iconic and enduring symbols of ancient Egyptian civilization. From the Great Pyramid of Khufu to the Sphinx and the surrounding complex of tombs and temples, the Pyramids of Giza are a must-visit attraction for history and archaeology enthusiasts.",
            // type: '',
        },
        {
            itinerary_id: '6028574319',
            user_id: '4976132085',
            user_name: 'GlobeTrotterGuy',
            user_icon: 'http://localhost:8080/images/users/Luke.jpg',
            city: 'Cairo, Eygpt',
            budget: '$',
            views: 7892,
            likes: 458,
            ratings: 4.4,
            duration: 5,
            city_img: 'http://localhost:8080/images/cities/cairo2.jpg',
            trip_title: "Nile River Cruise: Savoring the Scenic Beauty of Egypt's Lifeline",
            date: '08/16/2017',
            description: "Experience the majestic Nile River in all its glory on a scenic cruise that takes you past some of Cairo's most iconic landmarks and natural wonders. From the towering minarets and domes of the city's mosques to the tranquil beauty of the riverbanks and surrounding countryside, a Nile River cruise is a peaceful and breathtaking way to experience Cairo.",
            // type: '',
        },
        {
            itinerary_id: '9742160583',
            user_id: '4819062379',
            user_name: 'AlexaA',
            user_icon: 'http://localhost:8080/images/users/alexa.png',
            city: 'Beijing, China',
            budget: '$$$',
            views: 11629,
            likes: 6082,
            ratings: 4.5,
            duration: 5,
            city_img: 'http://localhost:8080/images/cities/beijing3.jpg',
            trip_title: "Forbidden City: Discovering the Secrets of Beijing's Imperial Past",
            date: '06/01/2018',
            description: "Step back in time and explore the ancient halls and courtyards of the Forbidden City, once the heart of the Chinese empire and the residence of countless emperors and their families. ",
            // type: '',
        },
        {
            itinerary_id: '3680452197',
            user_id: '1582973460',
            user_name: 'ZonningoutZ',
            user_icon: 'http://localhost:8080/images/users/zesty.png',
            city: 'Beijing, China',
            budget: '$$',
            views: 7,
            likes: 1,
            ratings: 0,
            duration: 10,
            city_img: 'http://localhost:8080/images/cities/beijing2.jpg',
            trip_title: "Discovering Beijing: A Modern Metropolis with a Rich Cultural Heritage",
            date: '09/21/2019',
            description: "Beijing is the bustling capital city of China, with a rich history that spans over 3,000 years. It is a modern metropolis that also serves as a cultural and political hub, boasting some of the world's most famous landmarks and attractions.",
            // type: '',
        },
        {
            itinerary_id: '8916230745',
            user_id: '6078925341',
            user_name: 'BrazilianLocalJa',
            user_icon: 'http://localhost:8080/images/users/jess.png',
            city: 'Shanghai, China',
            budget: '$$',
            views: 9925,
            likes: 7820,
            ratings: 4.5,
            duration: 7,
            city_img: 'http://localhost:8080/images/cities/shanghai.jpg',
            trip_title: "The Bund: Experiencing the Intersection of Old and New in Shanghai",
            date: '05/06/2018',
            description: "Wander along the Bund, a historic waterfront promenade that showcases the unique blend of Chinese and Western architecture that characterizes modern-day Shanghai. With stunning views of the city skyline and the Huangpu River, the Bund is a popular destination for locals and tourists alike.",
            // type: '',
        },
        {
            itinerary_id: '5412736098',
            user_id: '6815302947',
            user_name: 'WanderingWave',
            user_icon: 'http://localhost:8080/images/users/maya.jpg',
            city: 'Masai Mara, Kenya',
            budget: '$$',
            views: 1086,
            likes: 357,
            ratings: 4.3,
            duration: 8,
            city_img: 'http://localhost:8080/images/cities/kenya.jpg',
            trip_title: "Discover the Wonders of Kenya: A Safari Adventure",
            date: '11/03/2019',
            description: "Kenya is a magical destination that offers a wealth of opportunities for tourists to explore its rich wildlife, landscapes, and culture.",
            // type: '',
        },
        {
            itinerary_id: '7082164953',
            user_id: '4819062379',
            user_name: 'AlexaA',
            user_icon: 'http://localhost:8080/images/users/alexa.png',
            city: 'Accra, Ghana',
            budget: '$',
            views: 6702,
            likes: 568,
            ratings: 4.2,
            duration: 7,
            city_img: 'http://localhost:8080/images/cities/ghana.jpg',
            trip_title: "Discovering Ghana: A Land of Culture, History, and Natural Beauty",
            date: '01/18/2021',
            description: " Ghana is a vibrant country located in West Africa, known for its rich history, diverse culture, and stunning landscapes. From exploring ancient forts and castles to witnessing the majesty of the wildlife, Ghana offers a unique and unforgettable experience for travelers seeking adventure, education, and inspiration.",
            // type: '',
        },
        {
            itinerary_id: '9537140268',
            user_id: '6078925341',
            user_name: 'BrazilianLocalJa',
            user_icon: 'http://localhost:8080/images/users/jess.png',
            city: 'El nido, Philippines',
            budget: '$',
            views: 6902,
            likes: 832,
            ratings: 4.7,
            duration: 5,
            city_img: 'http://localhost:8080/images/cities/elnido.jpg',
            trip_title: "Paradise Found: Exploring the Natural Wonders of El Nido, Philippines",
            date: '05/11/2019',
            description: "El Nido is a tropical paradise located in the northern part of Palawan, Philippines. With its crystal-clear waters, stunning limestone cliffs, and abundant marine life, it is a haven for beach lovers, adventurers, and nature enthusiasts. Immerse yourself in the natural beauty of El Nido, and experience the peace, tranquility, and wonder of this hidden gem.",
            // type: '',
        },

        {
            itinerary_id: '2065813795',
            user_id: '630163fc-69c5-4745-ab50-e65fba71ea22',
            user_name: 'lintravels',
            user_icon: 'http://localhost:8080/images/users/sushi.jpg',
            city: 'New York City, USA',
            budget: '$$',
            views: 0,
            likes: 0,
            ratings: 0,
            duration: 3,
            city_img: 'http://localhost:8080/images/cities/nyc5.jpg',
            trip_title: "The Big Apple Awaits: Exploring the Best of New York City",
            date: '06/16/2022',
            description: "Discover the vibrant energy of NYC, from the iconic landmarks of the Statue of Liberty and the Empire State Building to the world-famous museums and galleries of Museum Mile.",
        },

    ]);
};
