exports.seed = async function (knex) {
    // Deletes ALL existing entries
    await knex('day').del();
    await knex('day').insert([
        {
            itinerary_id: '4829650317',
            user_name: 'RoamingRaven',
            city: 'tokyo, japan',
            day1: '',
            activity_id: '',
            activity_id: '',
            activity_id: '',
            activity_id: '',
            activity_id: '',

        },
        {
            itinerary_id: '4829650317',
            user_name: 'RoamingRaven',
            city: 'tokyo, japan',
            day2: '',
            activity1: '',
            activity_id: '',
            activity_id: '',
            activity_id: '',
            activity_id: '',
            activity_id: '',

        },
        {
            itinerary_id: '4829650317',
            user_name: 'RoamingRaven',
            city: 'tokyo, japan',
            day3: '',
            activity1: '',
            activity_id: '',
            activity_id: '',
            activity_id: '',
            activity_id: '',

        },
        {
            itinerary_id: '4829650317',
            user_name: 'RoamingRaven',
            city: 'tokyo, japan',
            day4: '',
            activity1: '',
            activity_id: '',
            activity_id: '',
            activity_id: '',
            activity_id: '',
            activity_id: '',
            activity_id: '',

        },
        {
            itinerary_id: '4829650317',
            user_name: 'RoamingRaven',
            city: 'tokyo, japan',
            day5: '',
            activity1: '',
            activity_id: '',
            activity_id: '',
            activity_id: '',
            activity_id: '',
            activity_id: '',
        },

        {
            itinerary_id: '1208376945',
            user_name: 'WanderingWave',
            city: 'tokyo, japan',
            day1: '',
            activity1: '',
            activity_id: '',
            activity_id: '',
            activity_id: '',
            activity_id: '',
        },
        {
            itinerary_id: '1208376945',
            user_name: 'WanderingWave',
            city: 'tokyo, japan',
            day2: '',
            activity1: '',
            activity_id: '',
            activity_id: '',
            activity_id: '',
            activity_id: '',
            activity_id: '',


        },
        {
            itinerary_id: '1208376945',
            user_name: 'WanderingWave',
            city: 'tokyo, japan',
            day3: '',
            activity1: '',
            activity_id: '',
            activity_id: '',
            activity_id: '',
            activity_id: '',
        },


        {
            itinerary_id: '6093842157',
            user_name: 'JetSetJenny',
            city: 'tokyo, japan',
            day1: '',
            activity1: '',
            activity_id: '',
            activity_id: '',
            activity_id: '',
            activity_id: '',

        },
        {
            itinerary_id: '6093842157',
            user_name: 'JetSetJenny',
            city: 'tokyo, japan',
            day2: '',
            activity1: '',
            activity_id: '',
            activity_id: '',
            activity_id: '',
            activity_id: '',

        },
        {
            itinerary_id: '6093842157',
            user_name: 'JetSetJenny',
            city: 'tokyo, japan',
            day3: '',
            activity1: '',
            activity_id: '',
            activity_id: '',
            activity_id: '',
            activity_id: '',

        },
        {
            itinerary_id: '6093842157',
            user_name: 'JetSetJenny',
            city: 'tokyo, japan',
            day4: '',
            activity1: '',
            activity_id: '',
            activity_id: '',
            activity_id: '',
            activity_id: '',

        },
        {
            itinerary_id: '6093842157',
            user_name: 'JetSetJenny',
            city: 'tokyo, japan',
            day5: '',
            activity1: '',
            activity_id: '',
            activity_id: '',
            activity_id: '',
            activity_id: '',

        },
        {
            itinerary_id: '6093842157',
            user_name: 'JetSetJenny',
            city: 'tokyo, japan',
            day6: '',
            activity1: '',
            activity_id: '',
            activity_id: '',
            activity_id: '',
            activity_id: '',

        },
        {
            itinerary_id: '6093842157',
            user_name: 'JetSetJenny',
            city: 'tokyo, japan',
            day7: '',
            activity1: '',
            activity_id: '',
            activity_id: '',
            activity_id: '',
            activity_id: '',

        },
        {
            itinerary_id: '6093842157',
            user_name: 'JetSetJenny',
            city: 'tokyo, japan',
            day8: '',
            activity1: '',
            activity_id: '',
            activity_id: '',
            activity_id: '',
            activity_id: '',

        },
        {
            itinerary_id: '6093842157',
            user_name: 'JetSetJenny',
            city: 'tokyo, japan',
            day9: '',
            activity1: '',
            activity_id: '',
            activity_id: '',
            activity_id: '',
            activity_id: '',

        },
        {
            itinerary_id: '6093842157',
            user_name: 'JetSetJenny',
            city: 'tokyo, japan',
            day10: '',
            activity1: '',
            activity_id: '',
            activity_id: '',
            activity_id: '',
            activity_id: '',

        },

        {
            itinerary_id: '3584217960',
            user_name: 'DaringAmy',
            city: 'London, uk',
            duration: 7,

        },
        {
            itinerary_id: '7491058362',
            user_name: 'NomadNate',
            city: 'London, uk',
            duration: 3,
        },
        {
            itinerary_id: '9316742085',
            user_name: 'BrazilianLocalJa',
            city: 'London, uk',
            duration: 5,
        },
        {
            itinerary_id: '2065813794',
            user_name: 'RoamingRaven',
            city: 'new york city',
            duration: 3,
        },
        {
            itinerary_id: '8576931024',
            user_name: 'DaringAmy',
            city: 'new york city',
            duration: 2,
        },
        {
            itinerary_id: '5132879460',
            user_name: 'AdventurousAnna',
            city: 'new york city',
            duration: 6,
        },
        {
            itinerary_id: '9753216840',
            user_name: 'NomadNate',
            city: 'new york city',
            budget: '$$',
            duration: 2,
        },
        {
            itinerary_id: '6743192850',
            user_name: 'JetSetJenny',
            city: 'new york city',
            duration: 7,
            city_img: 'http://localhost:8080/images/cities/nyc4.jpg',
        },

        {
            itinerary_id: '1248630975',
            user_name: 'GlobeTrotterGuy',
            city: 'chicago',
            day1_id: 'chi-guy-day1',
            activity_id: 'chi-4237659180987',
            activity_id: 'chi-9023487654321',
            activity_id: 'chi-9783075584516',
            activity_id: 'chi-2309587061234',
            activity_id: 'chi-9102381756089',
            activity_id: 'chi-7710238479654',

        },
        {
            itinerary_id: '1248630975',
            user_name: 'GlobeTrotterGuy',
            city: 'chicago',
            day2_id: 'chi-guy-day2',
            activity_id: 'chi-6458321487291',
            activity_id: 'chi-3928671151243',
            activity1: 'chi-3450986732109',
            activity_id: 'chi-1986734590876',
            activity_id: 'chi-6578910342569',
            activity_id: 'chi-6578910342569',
            activity_id: 'chi-6830421534790',

        },
        {
            itinerary_id: '1248630975',
            user_name: 'GlobeTrotterGuy',
            city: 'chicago',
            day3_id: 'chi-guy-day3',
            activity1: 'chi-2938465190783',
            activity_id: 'chi-5167903248170',
            activity_id: 'chi-3948601245809',
            activity_id: 'chi-7569193596049',
            activity_id: 'chi-7532910486709',
            activity_id: 'chi-2380569935861',
            activity_id: 'chi-5561876512399',


        },
        {
            itinerary_id: '1248630975',
            user_name: 'GlobeTrotterGuy',
            city: 'chicago',
            day4_id: 'chi-guy-day4',
            activity_id: 'chi-6458321487291',
            activity1: 'chi-6432908175362',
            activity_id: 'chi-3120765489032',
            activity_id: 'chi-3114788004565',

        },
        {
            itinerary_id: '1248630975',
            user_name: 'GlobeTrotterGuy',
            city: 'chicago',
            day5_id: 'chi-guy-day5',
            activity1: 'chi-4298710365498',
            activity_id: 'chi-7084632109854',
            activity_id: 'chi-5432109876345',
            activity_id: 'chi-8110121822778',
            activity_id: 'chi-7240954826703',
        },

        {
            itinerary_id: '3560829147',
            user_name: 'WanderingWave',
            city: 'chicago',
            day1_id: 'chi-wave-day1',
            activity_id: 'chi-6458321487291',
            activity_id: 'chi-3928671151243',
            activity_id: 'chi-2380569935861',
            activity1: 'chi-9023487654321',
            activity_id: 'chi-8765490123870',
            activity_id: 'chi-1354678902341',
            activity_id: 'chi-9804321765098',
            activity_id: 'chi-8712369851203',

        },
        {
            itinerary_id: '3560829147',
            user_name: 'WanderingWave',
            city: 'chicago',
            day2_id: 'chi-wave-day2',
            activity1: 'chi-3901248765032',
            activity_id: 'chi-7860543291805',
            activity_id: 'chi-3450986732109',
            activity_id: 'chi-9783075584516',
            activity_id: 'chi-7321659087432',

        },
        {
            itinerary_id: '3560829147',
            user_name: 'WanderingWave',
            city: 'chicago',
            day3_id: 'chi-wave-day3',
            activity1: 'chi-1986734590876',
            activity_id: 'chi-7084632109854',
            activity_id: 'chi-2304981765901',
            activity_id: 'chi-3120765489032',
            activity_id: 'chi-3114788004565',
            activity_id: 'chi-4069837123561',

        },


        {
            itinerary_id: '6925108347',
            user_name: 'NomadNate',
            city: 'paris, france',
            duration: 5,
        },
        {
            itinerary_id: '8316092754',
            user_name: 'DaringAmy',
            city: 'paris, france',
            duration: 4,
        },
        {
            itinerary_id: '2750691483',
            user_name: 'RoamingRaven',
            city: 'paris, france',
            duration: 3,
        },
        {
            itinerary_id: '4091567283',
            user_name: 'AdventurousAnna',
            city: 'paris, france',
            duration: 7,
        },
        {
            itinerary_id: '6280351974',
            user_name: 'GlobeTrotterGuy',
            city: 'paris, france',
            duration: 3,
        },
        {
            itinerary_id: '9378461025',
            user_name: 'BrazilianLocalJa',
            city: 'rome, italy',
            duration: 6,
        },
        {
            itinerary_id: '5082371649',
            user_name: 'BrazilianLocalJa',
            city: 'rome, italy',
            duration: 5,
        },
        {
            itinerary_id: '4265809731',
            user_name: 'DaringAmy',
            city: 'milan, italy',
            duration: 3,
        },
        {
            itinerary_id: '9481750236',
            user_name: 'NomadNate',
            city: 'venice, italy',
            duration: 3,
        },
        {
            itinerary_id: '3059274618',
            user_name: 'BrazilianLocalJa',
            city: 'bangkok, thailand',
            duration: 6,
        },
        {
            itinerary_id: '6827315490',
            user_name: 'WanderingWave',
            city: 'bangkok, thailand',
            duration: 10,
        },
        {
            itinerary_id: '9712356480',
            user_name: 'GlobeTrotterGuy',
            city: 'bangkok, thailand',
            duration: 2,
        },
        {
            itinerary_id: '7410293658',
            user_name: 'NomadNate',
            city: 'hanoi, vietnam',
            duration: 6,
        },
        {
            itinerary_id: '2106853479',
            user_name: 'DaringAmy',
            city: 'santorini, greece',
            duration: 5,
        },
        {
            itinerary_id: '5672981340',
            user_name: 'JetSetJenny',
            city: 'santorini, greece',
            duration: 9,
        },
        {
            itinerary_id: '8374051962',
            user_name: 'DaringAmy',
            city: 'amsterdam, netherland',
            duration: 5,
        },
        {
            itinerary_id: '2634809157',
            user_name: 'BrazilianLocalJa',
            city: 'amsterdam, netherland',
            duration: 3,
        },
        {
            itinerary_id: '4156092873',
            user_name: 'GlobeTrotterGuy',
            city: 'amsterdam, netherland',
            duration: 4,
        },
        {
            itinerary_id: '9267431508',
            user_name: 'BrazilianLocalJa',
            city: 'rio de janeiro, brazil',
            duration: 10,
        },
        {
            itinerary_id: '1785934620',
            user_name: 'WanderingWave',
            city: 'rio de janeiro, brazil',
            duration: 5,
        },
        {
            itinerary_id: '5801273649',
            user_name: 'DaringAmy',
            city: 'rio de janeiro, brazil',
            duration: 7,
        },
        {
            itinerary_id: '3048562791',
            user_name: 'NomadNate',
            city: 'lisbon, portugal',
            duration: 6,
        },
        {
            itinerary_id: '7913462058',
            user_name: 'DaringAmy',
            user_icon: 'http://localhost:8080/images/users/amy.png',
            duration: 3,
        },
        {
            itinerary_id: '1056829374',
            user_name: 'GlobeTrotterGuy',
            city: 'lisbon, portugal',
            duration: 5,
        },
        {
            itinerary_id: '4291638750',
            user_name: 'AdventurousAnna',
            city: 'lisbon, portugal',
            duration: 3,
        },
        {
            itinerary_id: '6835912470',
            user_name: 'DaringAmy',
            city: 'reykjavik iceland',
            duration: 10,
        },
        {
            itinerary_id: '8452069371',
            user_name: 'AlexaA',
            city: 'reykjavik iceland',
            duration: 4,
        },
        {
            itinerary_id: '5089362741',
            user_name: 'TumblingTom',
            city: 'singapore',
            duration: 2,
        },
        {
            itinerary_id: '1298437605',
            user_name: 'AdventurousAnna',
            city: 'singapore',
            duration: 3,
        },
        {
            itinerary_id: '2461587930',
            user_name: 'GlobeTrotterGuy',
            city: 'barcelona, spain',
            duration: 3,
        },
        {
            itinerary_id: '5729186304',
            user_name: 'AdventurousAnna',
            city: 'barcelona, spain',
            duration: 3,
        },
        {
            itinerary_id: '8714620935',
            user_name: 'DaringAmy',
            city: 'madrid, spain',
            duration: 4,
        },
        {
            itinerary_id: '3459726180',
            user_name: 'TumblingTom',
            city: 'cairo, eygpt',
            duration: 3,
        },
        {
            itinerary_id: '6028574319',
            user_name: 'GlobeTrotterGuy',
            city: 'cairo, eygpt',
            duration: 5,
        },
        {
            itinerary_id: '9742160583',
            user_name: 'AlexaA',
            city: 'beijing, china',
            duration: 5,
        },
        {
            itinerary_id: '3680452197',
            user_name: 'ZonningoutZ',
            city: 'beijing, china',
            duration: 10,
        },
        {
            itinerary_id: '8916230745',
            user_name: 'BrazilianLocalJa',
            city: 'shanghai, china',
            duration: 7,
        },
        {
            itinerary_id: '5412736098',
            user_name: 'WanderingWave',
            city: 'Masai Mara, Kenya',
        },
        {
            itinerary_id: '7082164953',
            user_name: 'AlexaA',
            city: 'accra, ghana',
            duration: 7,
        },
        {
            itinerary_id: '9537140268',
            user_name: 'BrazilianLocalJa',
            city: 'el nido, philippines',
            duration: 5,
        },

    ]);
};