exports.seed = async function (knex) {
  // Deletes ALL existing entries
  await knex('post').del();
  await knex('post').insert([
    //   egypt, singapore
    {
      trip_id: '4829650317',
      user_name: 'RoamingRaven',
      user_icon: 'http://localhost:8080/images/avery.jpg',
      author: 'Avery Matthews',
      city: 'tokyo, japan',
      budget: '$$',
      views: 400,
      likes: 70,
      ratings: 4.5,
      duration: 5,
    },
    {
      trip_id: '1208376945',
      user_name: 'WanderingWave',
      user_icon: 'http://localhost:8080/images/maya.jpg',
      author: 'Maya Rivera',
      city: 'tokyo, japan',
      budget: '$$$',
      views: 789,
      likes: 45,
      ratings: 4.7,
      duration: 3,
    },
    {
      trip_id: '6093842157',
      user_name: 'JetSetJenny',
      user_icon: 'http://localhost:8080/images/Jennifer.jpg',
      author: 'Jennifer Lee',
      city: 'tokyo, japan',
      budget: '$$',
      views: 20,
      likes: 1,
      ratings: 4.2,
      duration: 10,
      // type: '',
    },
    {
      trip_id: '3584217960',
      user_name: 'DaringAmy',
      user_icon: 'http://localhost:8080/images/amy.png',
      author: 'Amy Armance',
      city: 'London, uk',
      budget: '$$',
      views: 99532,
      likes: 5622,
      ratings: 4,
      duration: 7,
      // type: '',
    },
    {
      trip_id: '7491058362',
      user_name: 'NomadNate',
      user_icon: 'http://localhost:8080/images/Nathan.jpg',
      author: 'Nathan Chen',
      city: 'London, uk',
      budget: '$$$',
      views: 6789,
      likes: 255,
      ratings: 4.5,
      duration: 3,
      // type: '',
    },
    {
      trip_id: '9316742085',
      user_name: 'BrazilianLocalJa',
      user_icon: 'http://localhost:8080/images/jess.png',
      author: 'Jess A',
      city: 'London, uk',
      budget: '$$',
      views: 5671,
      likes: 468,
      ratings: 4.8,
      duration: 7,
      // type: '',
    },
    {
      trip_id: '2065813794',
      user_name: 'RoamingRaven',
      user_icon: 'http://localhost:8080/images/avery.jpg',
      author: 'Avery Matthews',
      city: 'new york city',
      budget: '$$$$',
      views: '',
      likes: '',
      ratings: 4.1,
      duration: 3,
      // type: '',
    },
    {
      trip_id: '8576931024',
      user_name: 'DaringAmy',
      user_icon: 'http://localhost:8080/images/amy.png',
      author: 'Amy Armance',
      city: 'new york city',
      budget: '$$',
      views: 66943,
      likes: 8622,
      ratings: 4,
      duration: 2,
      // type: '',
    },
    {
      trip_id: '5132879460',
      user_name: 'AdventurousAnna',
      user_icon: 'http://localhost:8080/images/anna.jpg',
      author: 'Anna Nguyen',
      city: 'new york city',
      budget: '$$$',
      views: 65300,
      likes: 5557,
      ratings: 4.6,
      duration: 6,
      // type: '',
    },
    {
      trip_id: '9753216840',
      user_name: 'NomadNate',
      user_icon: 'http://localhost:8080/images/Nathan.jpg',
      author: 'Nathan Chen',
      city: 'new york city',
      budget: '$$',
      views: 11001,
      likes: 557,
      ratings: 4.5,
      duration: 2,
      // type: '',
    },
    {
      trip_id: '6743192850',
      user_name: 'JetSetJenny',
      user_icon: 'http://localhost:8080/images/Jennifer.jpg',
      author: 'Jennifer Lee',
      city: 'new york city',
      budget: '$$$$',
      views: 5,
      likes: 0,
      ratings: 3.9,
      duration: 7,
      // type: '',
    },
    {
      trip_id: '1248630975',
      user_name: 'GlobeTrotterGuy',
      user_icon: 'http://localhost:8080/images/Luke.jpg',
      author: 'Luke Harrison',
      city: 'chicago',
      budget: '$$$',
      views: 563,
      likes: 212,
      ratings: 4.5,
      duration: 5,
      // type: '',
    },
    {
      trip_id: '3560829147',
      user_name: 'WanderingWave',
      user_icon: 'http://localhost:8080/images/maya.jpg',
      author: 'Maya Rivera',
      city: 'chicago',
      budget: '$$',
      views: 7890,
      likes: 567,
      ratings: 3.9,
      duration: 3,
      // type: '',
    },
    {
      trip_id: '6925108347',
      user_name: 'NomadNate',
      user_icon: 'http://localhost:8080/images/Nathan.jpg',
      author: 'Nathan Chen',
      city: 'paris, france',
      budget: '$$$$',
      views: 45890,
      likes: 200,
      ratings: 4.9,
      duration: 5,
      // type: '',
    },
    {
      trip_id: '8316092754',
      user_name: 'DaringAmy',
      user_icon: 'http://localhost:8080/images/amy.png',
      author: 'Amy Armance',
      city: 'paris, france',
      budget: '$$$',
      views: 11582,
      likes: 9986,
      ratings: 4.3,
      duration: 4,
      // type: '',
    },
    {
      trip_id: '2750691483',
      user_name: 'RoamingRaven',
      user_icon: 'http://localhost:8080/images/avery.jpg',
      author: 'Avery Matthews',
      city: 'paris, france',
      budget: '$$$',
      views: 5679,
      likes: 2343,
      ratings: 4.5,
      duration: 3,
      // type: '',
    },
    {
      trip_id: '4091567283',
      user_name: 'AdventurousAnna',
      user_icon: 'http://localhost:8080/images/anna.jpg',
      author: 'Anna Nguyen',
      city: 'paris, france',
      budget: '$$',
      views: 99521,
      likes: 5877,
      ratings: 4.1,
      duration: 7,
      // type: '',
    },
    {
      trip_id: '6280351974',
      user_name: 'GlobeTrotterGuy',
      user_icon: 'http://localhost:8080/images/Luke.jpg',
      author: 'Luke Harrison',
      city: 'paris, france',
      budget: '$$',
      views: 1930,
      likes: 378,
      ratings: 4.5,
      duration: 3,
      // type: '',
    },
    {
      trip_id: '9378461025',
      user_name: 'BrazilianLocalJa',
      user_icon: 'http://localhost:8080/images/jess.png',
      author: 'Jess A',
      city: 'paris, france',
      budget: '$$',
      views: 9722,
      likes: 678,
      ratings: 4.2,
      duration: 6,
      // type: '',
    },
    {
      trip_id: '5082371649',
      user_name: 'BrazilianLocalJa',
      user_icon: 'http://localhost:8080/images/jess.png',
      author: 'Jess A',
      city: 'rome, italy',
      budget: '$$',
      views: 90075,
      likes: 4267,
      ratings: 4.0,
      duration: 5,
      // type: '',
    },
    {
      trip_id: '4265809731',
      user_name: 'DaringAmy',
      user_icon: 'http://localhost:8080/images/amy.png',
      author: 'Amy Armance',
      city: 'rome, italy',
      budget: '$$',
      views: 77457,
      likes: 9975,
      ratings: 4.9,
      duration: 3,
      // type: '',
    },
    {
      trip_id: '9481750236',
      user_name: 'NomadNate',
      user_icon: 'http://localhost:8080/images/Nathan.jpg',
      author: 'Nathan Chen',
      city: 'venice, italy',
      budget: '$$$',
      views: 567,
      likes: 239,
      ratings: 4.2,
      duration: 3,
      // type: '',
    },
    {
      trip_id: '3059274618',
      user_name: 'BrazilianLocalJa',
      user_icon: 'http://localhost:8080/images/jess.png',
      author: 'Jess A',
      city: 'bankok, thailand',
      budget: '$$',
      views: 88932,
      likes: 45001,
      ratings: 4.5,
      duration: 6,
      // type: '',
    },
    {
      trip_id: '6827315490',
      user_name: 'WanderingWave',
      user_icon: 'http://localhost:8080/images/maya.jpg',
      author: 'Maya Rivera',
      city: 'bankok, thailand',
      budget: '$$',
      views: 12008,
      likes: 569,
      ratings: 3.5,
      duration: 10,
      // type: '',
    },
    {
      trip_id: '9712356480',
      user_name: 'GlobeTrotterGuy',
      user_icon: 'http://localhost:8080/images/Luke.jpg',
      author: 'Luke Harrison',
      city: 'bankok, thailand',
      budget: '$',
      views: 729,
      likes: 231,
      ratings: 4.1,
      duration: 2,
      // type: '',
    },
    {
      trip_id: '7410293658',
      user_name: 'NomadNate',
      user_icon: 'http://localhost:8080/images/Nathan.jpg',
      author: 'Nathan Chen',
      city: 'bankok, thailand',
      budget: '$$',
      views: 2097,
      likes: 702,
      ratings: 4,
      duration: 6,
      // type: '',
    },
    {
      trip_id: '2106853479',
      user_name: 'DaringAmy',
      user_icon: 'http://localhost:8080/images/amy.png',
      author: 'Amy Armance',
      city: 'santorini, greece',
      budget: '$$',
      views: 7795,
      likes: 347,
      ratings: 3.9,
      duration: 5,
      // type: '',
    },
    {
      trip_id: '5672981340',
      user_name: 'JetSetJenny',
      user_icon: 'http://localhost:8080/images/Jennifer.jpg',
      author: 'Jennifer Lee',
      city: 'santorini, greece',
      budget: '$$$',
      views: 74,
      likes: 10,
      ratings: 3.1,
      duration: 9,
      // type: '',
    },
    {
      trip_id: '8374051962',
      user_name: 'DaringAmy',
      user_icon: 'http://localhost:8080/images/amy.png',
      author: 'Amy Armance',
      city: 'amsterdam, netherland',
      budget: '$$',
      views: 56890,
      likes: 4227,
      ratings: 4.6,
      duration: 5,
      // type: '',
    },
    {
      trip_id: '2634809157',
      user_name: 'BrazilianLocalJa',
      user_icon: 'http://localhost:8080/images/jess.png',
      author: 'Jess A',
      city: 'amsterdam, netherland',
      budget: '$$',
      views: 5521,
      likes: 883,
      ratings: 4.2,
      duration: 3,
      // type: '',
    },
    {
      trip_id: '4156092873',
      user_name: 'GlobeTrotterGuy',
      user_icon: 'http://localhost:8080/images/Luke.jpg',
      author: 'Luke Harrison',
      city: 'amsterdam, netherland',
      budget: '$$',
      views: 781,
      likes: 129,
      ratings: 4.2,
      duration: 4,
      // type: '',
    },
    {
      trip_id: '9267431508',
      user_name: 'BrazilianLocalJa',
      user_icon: 'http://localhost:8080/images/jess.png',
      author: 'Jess A',
      city: 'rio de janeiro, brazil',
      budget: '$',
      views: 80991,
      likes: 67220,
      ratings: 4.9,
      duration: 10,
      // type: '',
    },
    {
      trip_id: '1785934620',
      user_name: 'WanderingWave',
      user_icon: 'http://localhost:8080/images/maya.jpg',
      author: 'Maya Rivera',
      city: 'rio de janeiro, brazil',
      budget: '$$',
      views: 674,
      likes: 237,
      ratings: 4.1,
      duration: 5,
      // type: '',
    },
    {
      trip_id: '5801273649',
      user_name: 'DaringAmy',
      user_icon: 'http://localhost:8080/images/amy.png',
      author: 'Amy Armance',
      city: 'rio de janeiro, brazil',
      budget: '$$',
      views: 88621,
      likes: 5990,
      ratings: 4.3,
      duration: 7,
      // type: '',
    },
    {
      trip_id: '3048562791',
      user_name: 'NomadNate',
      user_icon: 'http://localhost:8080/images/Nathan.jpg',
      author: 'Nathan Chen',
      city: 'lisbon, portugal',
      budget: '$$',
      views: 567,
      likes: 102,
      ratings: 4.2,
      duration: 6,
      // type: '',
    },
    {
      trip_id: '7913462058',
      user_name: 'DaringAmy',
      user_icon: 'http://localhost:8080/images/amy.png',
      author: 'Amy Armance',
      city: 'lisbon, portugal',
      budget: '$$$',
      views: 55292,
      likes: 6790,
      ratings: 4.2,
      duration: 3,
      // type: '',
    },
    {
      trip_id: '1056829374',
      user_name: 'GlobeTrotterGuy',
      user_icon: 'http://localhost:8080/images/Luke.jpg',
      author: 'Luke Harrison',
      city: 'lisbon, portugal',
      budget: '$',
      views: 567,
      likes: 213,
      ratings: 4.1,
      duration: 5,
      // type: '',
    },
    {
      trip_id: '4291638750',
      user_name: 'AdventurousAnna',
      user_icon: 'http://localhost:8080/images/anna.jpg',
      author: 'Anna Nguyen',
      city: 'lisbon, portugal',
      budget: '$$',
      views: 45190,
      likes: 2390,
      ratings: 3.2,
      duration: 3,
      // type: '',
    },
    {
      trip_id: '6835912470',
      user_name: 'DaringAmy',
      user_icon: 'http://localhost:8080/images/amy.png',
      author: 'Amy Armance',
      city: 'reykjavik iceland',
      budget: '$$',
      views: 77451,
      likes: 5422,
      ratings: 4.5,
      duration: 10,
      // type: '',
    },
    {
      trip_id: '8452069371',
      user_name: 'AlexaA',
      user_icon: 'http://localhost:8080/images/alexa.png',
      author: 'Alexa Casa',
      city: 'reykjavik iceland',
      budget: '$$$',
      views: 692,
      likes: 340,
      ratings: 4.5,
      duration: 4,
      // type: '',
    },
    {
      trip_id: '5089362741',
      user_name: 'TumblingTom',
      user_icon: 'Tommy Tom',
      author: 'http://localhost:8080/images/tommy.jpg',
      city: 'singapore',
      budget: '$$$',
      views: 50,
      likes: 6,
      ratings: 4.1,
      duration: 2,
      // type: '',
    },
    {
      trip_id: '1298437605',
      user_name: 'AdventurousAnna',
      user_icon: 'http://localhost:8080/images/anna.jpg',
      author: 'Anna Nguyen',
      city: 'singapore',
      budget: '$$$$',
      views: 70002,
      likes: 6890,
      ratings: 4.2,
      duration: 3,
      // type: '',
    },
    {
      trip_id: '2461587930',
      user_name: 'GlobeTrotterGuy',
      user_icon: 'http://localhost:8080/images/Luke.jpg',
      author: 'Luke Harrison',
      city: 'barcelona, spain',
      budget: '$$',
      views: 5672,
      likes: 123,
      ratings: 4.3,
      duration: 3,
      // type: '',
    },
    {
      trip_id: '5729186304',
      user_name: 'AdventurousAnna',
      user_icon: 'http://localhost:8080/images/anna.jpg',
      author: 'Anna Nguyen',
      city: 'barcelona, spain',
      budget: '$$',
      views: 14693,
      likes: 679,
      ratings: 3.6,
      duration: 3,
      // type: '',
    },
    {
      trip_id: '8714620935',
      user_name: 'DaringAmy',
      user_icon: 'http://localhost:8080/images/amy.png',
      author: 'Amy Armance',
      city: 'barcelona, spain',
      budget: '$$',
      views: 5521,
      likes: 760,
      ratings: 4.8,
      duration: 4
      // type: '',
    },
    {
      trip_id: '3459726180',
      user_name: 'TumblingTom',
      user_icon: 'http://localhost:8080/images/tommy.jpg',
      author: 'Tommy Tom',
      city: 'cairo, eygpt',
      budget: '$$$',
      views: 70,
      likes: 24,
      ratings: 4.2,
      duration: 3,
      // type: '',
    },
    {
      trip_id: '6028574319',
      user_name: 'GlobeTrotterGuy',
      user_icon: 'http://localhost:8080/images/Luke.jpg',
      author: 'Luke Harrison',
      city: 'cairo, eygpt',
      budget: '$',
      views: 7892,
      likes: 458,
      ratings: 4.4,
      duration: 5,
      // type: '',
    },
    {
      trip_id: '9742160583',
      user_name: 'AlexaA',
      user_icon: 'http://localhost:8080/images/alexa.png',
      author: 'Alexa Casa',
      city: 'beijing, china',
      budget: '$$$',
      views: 11629,
      likes: 6082,
      ratings: 4.5,
      duration: 5,
      // type: '',
    },
    {
      trip_id: '3680452197',
      user_name: 'ZonningoutZ',
      user_icon: 'http://localhost:8080/images/zesty.png',
      author: 'Zesty Zhao',
      city: 'beijing, china',
      budget: '$$',
      views: 7,
      likes: 1,
      ratings: 0,
      duration: 10,
      // type: '',
    },
    {
      trip_id: '8916230745',
      user_name: 'BrazilianLocalJa',
      user_icon: 'http://localhost:8080/images/jess.png',
      author: 'Jess A',
      city: 'shanghai, china',
      budget: '$$',
      views: 9925,
      likes: 7820,
      ratings: 4.5,
      duration: 7,
      // type: '',
    },
    {
      trip_id: '5412736098',
      user_name: 'WanderingWave',
      user_icon: 'http://localhost:8080/images/maya.jpg',
      author: 'Maya Rivera',
      city: 'johannesburg, south africa',
      budget: '$$',
      views: 1086,
      likes: 357,
      ratings: 4.3,
      duration: 8,
      // type: '',
    },
    {
      trip_id: '7082164953',
      user_name: 'AlexaA',
      user_icon: 'http://localhost:8080/images/alexa.png',
      author: 'Alexa Casa',
      city: 'accra, ghana',
      budget: '$',
      views: 6702,
      likes: 568,
      ratings: 4.2,
      duration: 7,
      // type: '',
    },
    {
      trip_id: '9537140268',
      user_name: 'BrazilianLocalJa',
      user_icon: 'http://localhost:8080/images/jess.png',
      author: 'Jess A',
      city: 'bora bora',
      budget: '$',
      views: 6902,
      likes: 832,
      ratings: 4.7,
      duration: 5,
      // type: '',
    },


  ]);
};
